# utils/sofa_wrapper.py
"""
Run a one–off SOFA/SoftRobots simulation on a tetrahedral mesh that
already contains an internal cavity.  Returns the bending angle (radians)
between the initial ‘base→tip’ axis and the final one after the cavity
is pressurised.

Requires:
    • SOFA-NG with SoftRobots and SofaPython3 plugins in $SOFA_ROOT
    • splib3 (comes with SoftRobots)
"""

import os, math
import numpy as np

# SOFA core -------------------------------------------------------
import SofaRuntime
SofaRuntime.importPlugin("SoftRobots")
SofaRuntime.importPlugin("SofaPython3")

import Sofa
from splib3.loaders import load  # convenience loader builds a FEM node


def _find_base_tip_indices(positions):
    """Return (base_idx, tip_idx) using min-Y / max-Y heuristic."""
    y = positions[:, 1]
    base = int(np.argmin(y))
    tip  = int(np.argmax(y))
    return base, tip


def run_sofa_once(mesh_path: str,
                  pressure_bar: float = 0.08,
                  n_steps: int = 400,
                  dt: float = 1 / 100.):
    """
    Parameters
    ----------
    mesh_path : str
        Path to a .msh tetrahedral mesh file generated by Gmsh.
    pressure_bar : float
        Internal pressure in MPa (0.08 ≈ 0.8 bar).
    n_steps : int
        Number of simulation steps.
    dt : float
        Fixed time-step size in seconds.

    Returns
    -------
    float
        Absolute bending angle in **radians** between initial and final
        tip vectors.
    """
    # ------------------- build scene root ------------------------
    root = Sofa.Core.Node("root")
    root.addObject("RequiredPlugin", pluginName="SoftRobots")
    root.gravity = [0.0, -9.81, 0.0]

    root.addObject("DefaultPipeline")
    root.addObject("BruteForceDetection")
    root.addObject("DefaultContactManager", response="FrictionContact")
    root.addObject("FreeMotionAnimationLoop")
    root.addObject("DefaultVisualManagerLoop")

    # ------------------- load tetrahedral body ------------------
    body, surf, _ = load(
        root,                      # parent
        mesh_path,                 # tetra mesh
        name="actuator",
        scale=[1.0, 1.0, 1.0],
        surfaceColor=[1.0, 0.6, 0.2, 1.0],
    )
    mo = body.getObject("dofs")  # MechanicalObject created by loader

    # FEM material and mass
    body.addObject(
        "TetrahedronFEMForceField",
        template="Vec3",
        method="large",
        poissonRatio=0.3,
        youngModulus=30e3,        # Pa
    )
    body.addObject("UniformMass", totalMass=0.05)

    # ------------------- pneumatic cavity -----------------------
    cavity = body.addChild("cavity")
    cavity.addObject("Mesh", filename=mesh_path)
    cavity.addObject(
        "SurfacePressureConstraint",
        name="pressure",
        template="Vec3",
        value=pressure_bar,       # MPa
        mappedSurface="@../..",   # acts on actuator surfaces
    )

    # ------------------- identify base / tip --------------------
    pos0 = np.array(mo.position.array())
    base_idx, tip_idx = _find_base_tip_indices(pos0)
    v0 = pos0[tip_idx] - pos0[base_idx]
    v0 /= np.linalg.norm(v0) + 1e-9  # normalised

    # ------------------- initialise and run ---------------------
    Sofa.Simulation.init(root)
    for _ in range(n_steps):
        Sofa.Simulation.animate(root, dt)

    # final positions
    pos = np.array(mo.position.array())
    v1 = pos[tip_idx] - pos[base_idx]
    v1 /= np.linalg.norm(v1) + 1e-9

    # bending angle (0 → straight, positive → bent)
    dot = np.clip(float(np.dot(v0, v1)), -1.0, 1.0)
    angle_rad = math.acos(dot)
    return angle_rad
